name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  check-file:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check student data file
        shell: cmd
        run: if exist studentdata.txt (echo File exists) else (exit /b 1)